[package]
name = "hedgecut"
version = "0.1.0"
authors = ["ssc <ssc@apache.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
csv = "1.1"
rand="0.6.5"
differential-dataflow = "0.11"
timely = "0.11"